import type { Metadata } from "next";
import { Inter, Heebo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "@/context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
const heebo = Heebo({ subsets: ["latin"], style: "normal" });

export const metadata: Metadata = {
  title: "Cecep Miftah Solahudin | Frontend Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth" suppressHydrationWarning>
      <body className={heebo.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
